//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW_Tuan08_Bai2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietdonhang
    {
        public int maDonHang { get; set; }
        public int maSach { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<decimal> donGia { get; set; }
    
        public virtual dondathang dondathang { get; set; }
        public virtual sach sach { get; set; }
    }
}
