//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW_Tuan08_Bai2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dondathang
    {
        public dondathang()
        {
            this.chitietdonhangs = new HashSet<chitietdonhang>();
        }
    
        public int maDonHang { get; set; }
        public string daThanhToan { get; set; }
        public string tinhtrangDonHang { get; set; }
        public Nullable<System.DateTime> ngayDat { get; set; }
        public Nullable<System.DateTime> ngayGiao { get; set; }
        public Nullable<int> maKH { get; set; }
    
        public virtual ICollection<chitietdonhang> chitietdonhangs { get; set; }
        public virtual khachhang khachhang { get; set; }
    }
}
