//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW_Tuan08_Bai2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachhang
    {
        public khachhang()
        {
            this.dondathangs = new HashSet<dondathang>();
        }
    
        public int maKH { get; set; }
        public string hoTen { get; set; }
        public string taiKhoan { get; set; }
        public string matKhau { get; set; }
        public string email { get; set; }
        public string diaChiKH { get; set; }
        public string dienThoaiKH { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
    
        public virtual ICollection<dondathang> dondathangs { get; set; }
    }
}
