//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW_Tuan08_Bai2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qltvEntities1 : DbContext
    {
        public qltvEntities1()
            : base("name=qltvEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<chitietdonhang> chitietdonhangs { get; set; }
        public DbSet<chude> chudes { get; set; }
        public DbSet<dondathang> dondathangs { get; set; }
        public DbSet<khachhang> khachhangs { get; set; }
        public DbSet<nhaxuatban> nhaxuatbans { get; set; }
        public DbSet<sach> saches { get; set; }
        public DbSet<tacgia> tacgias { get; set; }
        public DbSet<vietsach> vietsaches { get; set; }
    }
}
