//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW_Tuan08_Bai2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhaxuatban
    {
        public nhaxuatban()
        {
            this.saches = new HashSet<sach>();
        }
    
        public int maNXB { get; set; }
        public string tenNXB { get; set; }
        public string diaChi { get; set; }
        public string dienThoai { get; set; }
    
        public virtual ICollection<sach> saches { get; set; }
    }
}
