//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW_Tuan08_Bai2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sach
    {
        public sach()
        {
            this.chitietdonhangs = new HashSet<chitietdonhang>();
            this.vietsaches = new HashSet<vietsach>();
        }
    
        public int maSach { get; set; }
        public string tenSach { get; set; }
        public Nullable<decimal> giaBan { get; set; }
        public string moTa { get; set; }
        public string anhBia { get; set; }
        public Nullable<System.DateTime> ngayCapNhat { get; set; }
        public Nullable<int> soLuongTon { get; set; }
        public Nullable<int> maCD { get; set; }
        public Nullable<int> maNXB { get; set; }
    
        public virtual ICollection<chitietdonhang> chitietdonhangs { get; set; }
        public virtual chude chude { get; set; }
        public virtual nhaxuatban nhaxuatban { get; set; }
        public virtual ICollection<vietsach> vietsaches { get; set; }
    }
}
